// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgOJaBK5lnXTvEAYnN_pY4VDeSnujznD8',
    appId: '1:162835142166:web:49e7df115d220b032f0737',
    messagingSenderId: '162835142166',
    projectId: 'flutter-qoute',
    authDomain: 'flutter-qoute.firebaseapp.com',
    storageBucket: 'flutter-qoute.appspot.com',
    measurementId: 'G-85EVDM04HV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtMWeRKG071m0sAH3aeV8qrFuVgX3MXGg',
    appId: '1:162835142166:android:0c4f258166580c492f0737',
    messagingSenderId: '162835142166',
    projectId: 'flutter-qoute',
    storageBucket: 'flutter-qoute.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJQO_Vh5vGuMG2_OJ8xNhhMAXKvpEP-Go',
    appId: '1:162835142166:ios:b627137fe16ee3ff2f0737',
    messagingSenderId: '162835142166',
    projectId: 'flutter-qoute',
    storageBucket: 'flutter-qoute.appspot.com',
    iosClientId: '162835142166-d0tlcetjoo75mkn6s2v9i72o0trg38sc.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJQO_Vh5vGuMG2_OJ8xNhhMAXKvpEP-Go',
    appId: '1:162835142166:ios:b627137fe16ee3ff2f0737',
    messagingSenderId: '162835142166',
    projectId: 'flutter-qoute',
    storageBucket: 'flutter-qoute.appspot.com',
    iosClientId: '162835142166-d0tlcetjoo75mkn6s2v9i72o0trg38sc.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatting',
  );
}
